import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "UI Layout",
  description: "Generated by create next app",
};

export default function UILayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen items-center justify-center">{children}</div>
  );
}
